version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/todo_app
      - SECRET_KEY=change_this_in_production
      - JWT_SECRET_KEY=change_this_in_production
    depends_on:
      - db
    volumes:
      - ./:/app
    command: >
      bash -c "flask db upgrade && 
              gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app"

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: